spring:
  datasource:
    url: "jdbc:postgresql://${DB_HOST:192.168.103.106}:${DB_PORT:5432}/${DB_NAME:resource-storage-service}"
    username: "${DB_USERNAME:postgres}"
    password: "${DB_PASSWORD:123cp!@#}"
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 5
      minimum-idle: 1
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
      pool-name: StoragePool

  jpa:
    hibernate:
      ddl-auto: update   # auto-creates api_keys table + path_store column on first run
    show-sql: false

server:
  port: "${SERVER_PORT:7072}"

spaces:
  endpoint: "https://sgp1.digitaloceanspaces.com"
  region: "sgp1"
  bucket: "emenu-cambodia"
  access-key: "DO00QQ6TAV62YPV3DC4U"
  secret-key: "+ye4MKS7msULnLoNvmEy60KpBGaG8IWGepnTNrdTfTw"
  cdn-base-url: "https://emenu-cambodia.sgp1.cdn.digitaloceanspaces.com"
  store-on-database: true
  local-base-url: "http://localhost:${server.port}"
  admin-username: "phatmenghor"
  admin-password: "Hour1819"

logging:
  level:
    root: INFO
    org.springframework: WARN
    org.hibernate: WARN
