spring:
  datasource:
    url: "jdbc:postgresql://${DB_HOST:167.172.88.194}:${DB_PORT:5432}/${DB_NAME:resource-storage-service}"
    username: "${DB_USERNAME:resource-storage-users}"
    password: "${DB_PASSWORD:Hour1819}"
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
      pool-name: StoragePool

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

server:
  port: "${SERVER_PORT:7072}"

spaces:
  store-on-database: true
  local-base-url: "http://localhost:${server.port}"
  admin-username: "phatmenghor"
  admin-password: "Hour1819"

logging:
  level:
    root: INFO
    org.springframework: WARN
    org.hibernate: WARN
