-- Create 3 base subscription plans - one for each SubscriptionPlanDurationType enum value
-- IDs are auto-generated by the database (UUID v4)

INSERT INTO subscription_plans (name, description, price, status, duration_type, created_at, created_by, updated_at, updated_by, is_deleted)
VALUES
  (
    '1 Week',
    'Try the full platform completely free',
    0.00,
    'PUBLIC',
    'WEEKLY',
    NOW(),
    'SYSTEM',
    NOW(),
    'SYSTEM',
    false
  ),
  (
    '1 Month',
    'Full platform access, completely free',
    0.00,
    'PUBLIC',
    'MONTHLY',
    NOW(),
    'SYSTEM',
    NOW(),
    'SYSTEM',
    false
  ),
  (
    '1 Year',
    'Best value for serious businesses',
    0.00,
    'PUBLIC',
    'YEARLY',
    NOW(),
    'SYSTEM',
    NOW(),
    'SYSTEM',
    false
  )
ON CONFLICT (duration_type) DO NOTHING;
