services:
  backend:
    container_name: emenu_backend
    build:
      context: /opt/apps/emenu-backend
      dockerfile: Dockerfile
    image: emenu-cambodia/backend:1.0.0
    restart: unless-stopped
    volumes:
      - /opt/apps/emenu-backend/logs:/app/logs
    ports:
      - "7070:7070"
    environment:
      SPRING_PROFILES_ACTIVE: prod
    extra_hosts:
      - "host.docker.internal:host-gateway"
