-- ============================================================================
-- LOCATION DATA MIGRATION
-- Run PART A on SOURCE database → copy output → run PART B on PRODUCTION.
--
-- Production tables use UUID PKs (BaseUUIDEntity).
-- Source tables use bigint PKs; FK hierarchy is province→district→commune→village.
-- The production join keys are CODE columns (varchar), not IDs, so no UUID
-- mapping is needed — codes are copied directly.
--
-- Tables:
--   location_province_cbc
--   location_district_cbc   (FK: province_code)
--   location_commune_cbc    (FK: district_code)
--   location_village_cbc    (FK: commune_code)
-- ============================================================================


-- ============================================================================
-- PART A — Run on SOURCE database
-- Each query outputs ready-to-run INSERT statements.
-- Copy all rows from the "sql_statement" column and save as location-data.sql
-- ============================================================================

-- ── A1. Provinces ────────────────────────────────────────────────────────────
SELECT
  'INSERT INTO location_province_cbc '
  || '(id, version, is_deleted, created_at, updated_at, deleted_at, '
  || 'created_by, updated_by, deleted_by, province_code, province_en, province_kh) '
  || 'VALUES (gen_random_uuid(), 0, false, NOW(), NOW(), NULL, '
  || '''system'', ''system'', NULL, '''
  || replace(province_code, '''', '''''') || ''', '''
  || replace(COALESCE(province_en, ''), '''', '''''') || ''', '''
  || replace(COALESCE(province_kh, ''), '''', '''''')
  || ''') ON CONFLICT (province_code) DO NOTHING;'   AS sql_statement
FROM location_province_cbc
ORDER BY id;


-- ── A2. Districts ─────────────────────────────────────────────────────────────
-- JOINs to province to get province_code (source district table has bigint province_id)
SELECT
  'INSERT INTO location_district_cbc '
  || '(id, version, is_deleted, created_at, updated_at, deleted_at, '
  || 'created_by, updated_by, deleted_by, district_code, district_en, district_kh, province_code) '
  || 'VALUES (gen_random_uuid(), 0, false, NOW(), NOW(), NULL, '
  || '''system'', ''system'', NULL, '''
  || replace(d.district_code, '''', '''''') || ''', '''
  || replace(COALESCE(d.district_en, ''), '''', '''''') || ''', '''
  || replace(COALESCE(d.district_kh, ''), '''', '''''') || ''', '''
  || replace(p.province_code, '''', '''''')
  || ''') ON CONFLICT (district_code) DO NOTHING;'   AS sql_statement
FROM location_district_cbc d
JOIN location_province_cbc  p ON p.id = d.province_id
ORDER BY d.id;


-- ── A3. Communes ──────────────────────────────────────────────────────────────
SELECT
  'INSERT INTO location_commune_cbc '
  || '(id, version, is_deleted, created_at, updated_at, deleted_at, '
  || 'created_by, updated_by, deleted_by, commune_code, commune_en, commune_kh, district_code) '
  || 'VALUES (gen_random_uuid(), 0, false, NOW(), NOW(), NULL, '
  || '''system'', ''system'', NULL, '''
  || replace(c.commune_code, '''', '''''') || ''', '''
  || replace(COALESCE(c.commune_en, ''), '''', '''''') || ''', '''
  || replace(COALESCE(c.commune_kh, ''), '''', '''''') || ''', '''
  || replace(d.district_code, '''', '''''')
  || ''') ON CONFLICT (commune_code) DO NOTHING;'    AS sql_statement
FROM location_commune_cbc   c
JOIN location_district_cbc  d ON d.id = c.district_id
ORDER BY c.id;


-- ── A4. Villages ──────────────────────────────────────────────────────────────
SELECT
  'INSERT INTO location_village_cbc '
  || '(id, version, is_deleted, created_at, updated_at, deleted_at, '
  || 'created_by, updated_by, deleted_by, village_code, village_en, village_kh, commune_code) '
  || 'VALUES (gen_random_uuid(), 0, false, NOW(), NOW(), NULL, '
  || '''system'', ''system'', NULL, '''
  || replace(v.village_code, '''', '''''') || ''', '''
  || replace(COALESCE(v.village_en, ''), '''', '''''') || ''', '''
  || replace(COALESCE(v.village_kh, ''), '''', '''''') || ''', '''
  || replace(c.commune_code, '''', '''''')
  || ''') ON CONFLICT (village_code) DO NOTHING;'    AS sql_statement
FROM location_village_cbc  v
JOIN location_commune_cbc  c ON c.id = v.commune_id
ORDER BY v.id;


-- ============================================================================
-- PART B — Run on PRODUCTION database (after copying output from PART A)
-- Paste the INSERT statements generated by each query above and run them
-- in this order so FK constraints are satisfied:
--   1. Provinces first (no FK dependency)
--   2. Districts      (need province_code rows to exist)
--   3. Communes       (need district_code rows to exist)
--   4. Villages       (need commune_code rows to exist)
-- ============================================================================


-- ============================================================================
-- PART C — Verify row counts match between source and production
-- Run on PRODUCTION after migration:
-- ============================================================================
SELECT 'location_province_cbc' AS tbl, COUNT(*) FROM location_province_cbc WHERE is_deleted = false
UNION ALL
SELECT 'location_district_cbc',        COUNT(*) FROM location_district_cbc WHERE is_deleted = false
UNION ALL
SELECT 'location_commune_cbc',         COUNT(*) FROM location_commune_cbc  WHERE is_deleted = false
UNION ALL
SELECT 'location_village_cbc',         COUNT(*) FROM location_village_cbc  WHERE is_deleted = false
ORDER BY tbl;

-- Run the same COUNT query on SOURCE (without is_deleted filter) to compare:
-- SELECT 'province', COUNT(*) FROM location_province_cbc
-- UNION ALL SELECT 'district', COUNT(*) FROM location_district_cbc
-- UNION ALL SELECT 'commune',  COUNT(*) FROM location_commune_cbc
-- UNION ALL SELECT 'village',  COUNT(*) FROM location_village_cbc;
